---
format_version: '11'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: other
pipelines:
  pipeline_1:
    stages:
    - test: {}
stages:
  test:
    workflows:
    - primary: {}
    - primary: {}
workflows:
  primary:
    steps:
    - activate-ssh-key@4:
        run_if: '{{getenv "SSH_RSA_PRIVATE_KEY" | ne ""}}'
    - git-clone@6: {}
    - script@1:
        title: Get Pipeline Information
        inputs:
        - is_debug: 'yes'
        - content: |
            #!/usr/bin/env bash
            # fail if any commands fails
            set -e
            # make pipelines' return status equal the last command to exit with a non-zero status, or zero if all commands exit successfully
            set -o pipefail
            # debug log
            set -x

            curl -X 'GET' \
              "https://api.bitrise.io/v0.1/apps/$BITRISE_APP_SLUG/pipelines/$BITRISEIO_PIPELINE_ID" \
              -H "accept: application/json" \
              -H "Authorization: $BITRISE_TOKEN" | jq ".stages[0].workflows | map(.external_id == \"$BITRISE_BUILD_SLUG\") | index(true)"
    - deploy-to-bitrise-io@2: {}
meta:
  bitrise.io:
    stack: osx-xcode-13.3.x
    machine_type_id: g2.4core
app:
  envs:
  - opts:
      is_expand: false
    GIT_REPOSITORY_URL: git@github.com:atanas-bitrise/dynamic-demo.git
  - opts:
      is_expand: false
    BITRISE_GIT_BRANCH: main
